/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_Serial.h"
#include "isr_Serial.h"
#include "SDA_aliases.h"
#include "SDA.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "LCD_I2C_FUNCS.h"
#include "LCD_I2C_LL_I2C.h"
#include "LCD_I2C_REGS.h"
#include "Timer.h"
#include "timer_clock_1.h"
#include "timer_clock.h"
#include "isr_Timer.h"
#include "Trigger_aliases.h"
#include "Trigger.h"
#include "Trigger_in_aliases.h"
#include "Trigger_in.h"
#include "Out_1_aliases.h"
#include "Out_1.h"
#include "Out_4_aliases.h"
#include "Out_4.h"
#include "Out_3_aliases.h"
#include "Out_3.h"
#include "Out_2_aliases.h"
#include "Out_2.h"
#include "Counter.h"
#include "UART_Serial_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

